name: parachrsnp
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - snakemake-minimal
  - bwa
  - bwa-mem2
  - samtools
  - bcftools
  - gatk4
  - picard
  - fastp
  - plink
  - tassel
  - beagle
  - snpeff
  - imagemagick
  - librsvg
  - r-base
  - r-ape
  - r-dplyr
  - r-scatterplot3d
  - bioconductor-ggtree
  - pandas
  - numpy
  - matplotlib
  - pip
