reference: "reference/Arabidopsis_thaliana.fasta"

container:
    image: "ParaChrSNP_ape_ggtree.sif"

samples:
    ERR16804307: "raw_fastq/ERR16804307"
    ERR16805220: "raw_fastq/ERR16805220"
    ERR16805679: "raw_fastq/ERR16805679"
    ERR16806713: "raw_fastq/ERR16806713"
chromosomes:
  - NC_003070.9
  - NC_003071.7
  - NC_003074.8
  - NC_003075.7
  - NC_003076.8
params:
    qc:
        threads: 4
        extra: "--nozip"

    bwa:
        bwa_threads: 4

    fastp:
        fastp_threads: 4

    haplotype_caller:
        java_options: "--java-options \"-Xms512m -Xmx4g\""

    genotype_gvcfs:
        java_options: "--java-options \"-Xms512m -Xmx128g\""

    combine_vcf:
        java_options: "--java-options \"-Xms512m -Xmx128g\""

    snp_filter:
        filter_name: "SNP_filter"
        thresholds:
            qd: 2.0
            mq: 40.0
            fs: 60.0
            sor: 3.0
            mq_rank_sum: -12.5
            read_pos_rank_sum: -8.0

    indel_filter:
        filter_name: "INDEL_filter"
        thresholds:
            qd: 2.0
            fs: 200.0
            sor: 10.0
            mq_rank_sum: -12.5
            read_pos_rank_sum: -8.0

    vcf_missing:
        output_prefix: "missing/combined.snp.filtered"
        plot_prefix: "missing/combined.snp.filtered.miss_check"
        plot_script: "scripts/plink-missing.py"
        extra: "--allow-extra-chr"

    vcf_convert:
        input_vcf: "result_vcfs/combined.snp.filtered.vcf.gz"
        output_prefix: "format_convert/combined.snp.filtered"
        plink_extra: "--allow-extra-chr"
        tassel_executable: "run_pipeline.pl"
        tassel_memory: "-Xmx10g"
        tassel_extra: ""

    vcf2pca:
        enabled: true
        executable: "VCF2PCACluster"
        sample_group: ""
        output_prefix: "pca/ParaChrSNP"
        threads: 4
        extra: ""

    vcf2dis:
        enabled: true
        executable: "VCF2Dis"
        sample_group: ""
        output_matrix: "dis/ParaChrSNP.p_dis.mat"
        output_tree: "dis/ParaChrSNP.p_dis.nwk"
        tree_method: 1
        extra: ""
