#!/usr/bin/env Rscript

# Author: Junpeng Ma 1527552938@qq.com
# 功能：根据 PopLDdecay 整理后的结果绘制 LD 衰减曲线。

script_name <- "ld-decay-plot-nature_1.R"
script_path <- normalizePath(commandArgs(trailingOnly = FALSE)[1], mustWork = FALSE)

write_script_log <- function() {
  line <- paste(
    format(Sys.time(), "%Y-%m-%dT%H:%M:%S"),
    script_name,
    "Draw Nature-style LD decay curves from PopLDdecay output",
    script_path,
    sep = "\t"
  )
  suppressWarnings(try(write(line, file = "/home/majunpeng/script_log.txt", append = TRUE), silent = TRUE))
}

usage <- function() {
  cat("Usage: Rscript ld-decay-plot-nature_1.R --combined FILE --out FILE\n\n")
  cat("Options:\n")
  cat("  --combined FILE  Combined LD decay TSV generated by poplddecay-combine_1.py.\n")
  cat("  --out FILE       Output PDF file. PNG, SVG and TIFF files are generated with the same prefix.\n")
  cat("  -h, --help       Show this help message and exit.\n")
}

parse_args <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) == 1 && args[1] %in% c("-h", "--help")) {
    usage()
    quit(save = "no", status = 0)
  }
  opts <- list()
  i <- 1
  while (i <= length(args)) {
    key <- args[i]
    if (!startsWith(key, "--") || i == length(args)) {
      stop(paste("Invalid argument:", key))
    }
    opts[[substring(key, 3)]] <- args[i + 1]
    i <- i + 2
  }
  if (is.null(opts$combined) || is.null(opts$out)) {
    usage()
    quit(save = "no", status = 1)
  }
  opts
}

read_ld <- function(path) {
  df <- read.delim(path, stringsAsFactors = FALSE, check.names = FALSE)
  need <- c("population", "distance_bp", "r2")
  if (!all(need %in% names(df))) {
    stop("Input table must contain columns: population, distance_bp, r2")
  }
  df <- df[is.finite(df$distance_bp) & is.finite(df$r2), ]
  if (nrow(df) == 0) {
    stop("No valid LD decay rows found.")
  }
  df
}

save_all <- function(pdf_path, plot_fun) {
  dir.create(dirname(pdf_path), recursive = TRUE, showWarnings = FALSE)
  stem <- sub("\\.pdf$", "", pdf_path, ignore.case = TRUE)
  pdf(pdf_path, width = 7.2, height = 4.8, useDingbats = FALSE)
  plot_fun()
  dev.off()
  png(paste0(stem, ".png"), width = 2400, height = 1600, res = 300, type = "cairo")
  plot_fun()
  dev.off()
  svg(paste0(stem, ".svg"), width = 7.2, height = 4.8)
  plot_fun()
  dev.off()
  tiff(paste0(stem, ".tiff"), width = 2400, height = 1600, res = 300, compression = "lzw", type = "cairo")
  plot_fun()
  dev.off()
}

draw_plot <- function(df) {
  pops <- unique(df$population)
  palette <- c("#3B6FB6", "#D95F02", "#1B9E77", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D")
  cols <- rep(palette, length.out = length(pops))
  xlim <- range(df$distance_bp / 1000, na.rm = TRUE)
  ylim <- range(c(0, df$r2), na.rm = TRUE)
  par(mar = c(4.4, 4.6, 1.2, 1), mgp = c(2.6, 0.8, 0), las = 1, family = "sans")
  plot(
    NA,
    xlim = xlim,
    ylim = ylim,
    xlab = "Distance (kb)",
    ylab = expression(LD~(r^2)),
    bty = "l",
    xaxs = "i",
    yaxs = "i"
  )
  grid(col = "#E5E7EB", lwd = 0.45)
  for (i in seq_along(pops)) {
    sub <- df[df$population == pops[i], ]
    sub <- sub[order(sub$distance_bp), ]
    lines(sub$distance_bp / 1000, sub$r2, col = cols[i], lwd = 0.8)
  }
  legend("topright", legend = pops, col = cols, lwd = 1.1, bty = "n", cex = 0.85)
}

write_script_log()
opts <- parse_args()
ld <- read_ld(opts$combined)
save_all(opts$out, function() draw_plot(ld))
