#!/usr/bin/env Rscript

# 修改说明：
# 本脚本用于绘制 ParaChrSNP Pi 窗口统计结果的 Nature 风格曼哈顿图。
# 输入来自 scripts/pi-window_1.py 生成的 combined.windowed.pi.tsv。

script_name <- "pi-manhattan-nature_1.R"
script_function <- "Draw Nature-style Manhattan plot for windowed Pi results."
script_log <- "/home/majunpeng/script_log.txt"
script_path <- normalizePath(sub("--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]), mustWork = FALSE)
try(
  suppressWarnings(cat(
    format(Sys.time(), "%Y-%m-%d %H:%M:%S"), script_name, script_function, script_path, "Junpeng Ma 1527552938@qq.com\n",
    sep = "\t", file = script_log, append = TRUE
  )),
  silent = TRUE
)

usage <- paste(
  "Usage: Rscript scripts/pi-manhattan-nature_1.R --pi <combined.windowed.pi.tsv> --out <pdf> [--fai <reference.fa.fai>]",
  "",
  "Arguments:",
  "  --pi   Combined windowed Pi table generated by scripts/pi-window_1.py.",
  "  --out  Output PDF path. Matching PNG, SVG and TIFF files are also written.",
  "  --fai  Optional FASTA index used to order chromosomes.",
  "",
  "Author: Junpeng Ma 1527552938@qq.com",
  sep = "\n"
)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 1 && args[1] %in% c("-h", "--help")) {
  cat(usage, "\n")
  quit(status = 0)
}

get_arg <- function(flag, default = NA_character_, required = TRUE) {
  hit <- which(args == flag)
  if (length(hit) == 0 || hit[1] == length(args)) {
    if (required) stop("Missing argument: ", flag)
    return(default)
  }
  args[hit[1] + 1]
}

pi_path <- get_arg("--pi")
out_pdf <- get_arg("--out")
fai_path <- get_arg("--fai", default = "", required = FALSE)

pi_data <- read.delim(pi_path, stringsAsFactors = FALSE, check.names = FALSE)
required_cols <- c("population", "CHROM", "BIN_START", "BIN_END", "N_VARIANTS", "PI")
missing_cols <- setdiff(required_cols, colnames(pi_data))
if (length(missing_cols) > 0) {
  stop("Missing required columns in Pi table: ", paste(missing_cols, collapse = ", "))
}

pi_data$BIN_START <- suppressWarnings(as.numeric(pi_data$BIN_START))
pi_data$BIN_END <- suppressWarnings(as.numeric(pi_data$BIN_END))
pi_data$PI <- suppressWarnings(as.numeric(pi_data$PI))
pi_data$N_VARIANTS <- suppressWarnings(as.numeric(pi_data$N_VARIANTS))
pi_data <- pi_data[is.finite(pi_data$BIN_START) & is.finite(pi_data$BIN_END) & is.finite(pi_data$PI), , drop = FALSE]
if (nrow(pi_data) == 0) {
  stop("No valid Pi windows were found.")
}

if (!is.na(fai_path) && nzchar(fai_path) && file.exists(fai_path)) {
  fai <- read.delim(fai_path, header = FALSE, stringsAsFactors = FALSE)
  chrom_order <- fai[[1]][fai[[1]] %in% unique(pi_data$CHROM)]
  chrom_order <- c(chrom_order, setdiff(unique(pi_data$CHROM), chrom_order))
} else {
  chrom_order <- unique(pi_data$CHROM)
}

pi_data$CHROM <- factor(pi_data$CHROM, levels = chrom_order)
pi_data <- pi_data[order(pi_data$CHROM, pi_data$BIN_START, pi_data$population), , drop = FALSE]

chrom_lengths <- aggregate(BIN_END ~ CHROM, pi_data, max)
chrom_lengths <- chrom_lengths[match(chrom_order, as.character(chrom_lengths$CHROM)), , drop = FALSE]
chrom_lengths <- chrom_lengths[!is.na(chrom_lengths$CHROM), , drop = FALSE]
offset <- c(0, cumsum(head(chrom_lengths$BIN_END, -1)))
names(offset) <- as.character(chrom_lengths$CHROM)
chrom_mid <- offset + chrom_lengths$BIN_END / 2

pi_data$midpoint <- (pi_data$BIN_START + pi_data$BIN_END) / 2
pi_data$xpos <- pi_data$midpoint + offset[as.character(pi_data$CHROM)]

populations <- unique(pi_data$population)
base <- sub("\\.pdf$", "", out_pdf, ignore.case = TRUE)
dir.create(dirname(out_pdf), recursive = TRUE, showWarnings = FALSE)

palette <- c("#3B6FB6", "#9A9A9A")
point_cols <- palette[(as.integer(pi_data$CHROM) - 1) %% length(palette) + 1]

draw_plot <- function() {
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par), add = TRUE)
  n_pop <- length(populations)
  par(
    mfrow = c(n_pop, 1),
    mar = c(ifelse(n_pop == 1, 4.3, 2.5), 4.2, 1.0, 0.8),
    oma = c(1.5, 0, 0.5, 0),
    mgp = c(2.3, 0.65, 0),
    tcl = -0.25,
    family = "Arial",
    las = 1,
    xaxs = "i"
  )
  for (i in seq_along(populations)) {
    pop <- populations[i]
    subset_data <- pi_data[pi_data$population == pop, , drop = FALSE]
    subset_cols <- point_cols[pi_data$population == pop]
    ylim_max <- max(subset_data$PI, na.rm = TRUE)
    if (!is.finite(ylim_max) || ylim_max <= 0) {
      ylim_max <- 1
    }
    plot(
      subset_data$xpos,
      subset_data$PI,
      pch = 16,
      cex = 0.42,
      col = subset_cols,
      xaxt = "n",
      xlab = "",
      ylab = expression(pi),
      ylim = c(0, ylim_max * 1.08),
      bty = "l",
      cex.axis = 0.72,
      cex.lab = 0.82
    )
    grid(nx = NA, ny = NULL, col = "#E8E8E8", lwd = 0.45)
    mtext(pop, side = 3, adj = 0, line = 0.15, cex = 0.78, font = 2)
    if (i == n_pop) {
      axis(1, at = chrom_mid, labels = names(chrom_mid), las = 2, cex.axis = 0.62)
      mtext("Chromosome", side = 1, line = 3.7, cex = 0.82)
    }
  }
}

height_in <- max(2.6, 1.6 * length(populations) + 1.0)
width_in <- 7.1

svg(paste0(base, ".svg"), width = width_in, height = height_in, family = "Arial")
draw_plot()
dev.off()

png(paste0(base, ".png"), width = width_in, height = height_in, units = "in", res = 300, type = "cairo")
draw_plot()
dev.off()

cairo_pdf(out_pdf, width = width_in, height = height_in, family = "Arial")
draw_plot()
dev.off()

tiff(paste0(base, ".tiff"), width = width_in, height = height_in, units = "in", res = 600, compression = "lzw")
draw_plot()
dev.off()
