#!/usr/bin/env Rscript

# 修改说明：
# 本脚本基于 scripts/plink-missing.R 和 scripts/plink-missing.py 的输入输出接口重新生成。
# 目标是使用 R/ggplot2 输出符合 Nature 风格的 PLINK 缺失率分布图。
# 原始脚本位置：scripts/plink-missing.R；Python 改写版位置：scripts/plink-missing.py。

script_name <- "plink-missing-nature_1.R"
script_function <- "Draw Nature-style PLINK missingness histograms with R."
script_log <- "/home/majunpeng/script_log.txt"
script_path <- normalizePath(sub("--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]), mustWork = FALSE)
try(
  suppressWarnings(cat(
    format(Sys.time(), "%Y-%m-%d %H:%M:%S"), script_name, script_function, script_path, "\n",
    sep = "\t", file = script_log, append = TRUE
  )),
  silent = TRUE
)

usage <- paste(
  "Usage: Rscript scripts/plink-missing-nature_1.R <plink.lmiss> <plink.imiss> <out.prefix>",
  "",
  "Arguments:",
  "  <plink.lmiss>   PLINK variant-level missingness table generated by plink --missing.",
  "  <plink.imiss>   PLINK sample-level missingness table generated by plink --missing.",
  "  <out.prefix>    Output prefix. The script writes PDF, SVG and TIFF figures.",
  "",
  "Outputs:",
  "  <out.prefix>.sample_missing.pdf/.svg/.tiff",
  "  <out.prefix>.Variant_missing.pdf/.svg/.tiff",
  sep = "\n"
)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 1 && args[1] %in% c("-h", "--help")) {
  cat(usage, "\n")
  quit(status = 0)
}
if (length(args) != 3) {
  cat(usage, "\n", file = stderr())
  quit(status = 1)
}

suppressPackageStartupMessages({
  library(ggplot2)
  library(scales)
})

lfile <- args[1]
ifile <- args[2]
prefix <- args[3]

read_missing <- function(path) {
  # 读取 PLINK 输出的空白分隔表，并检查 F_MISS 是否存在。
  dat <- read.table(path, header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
  if (!"F_MISS" %in% colnames(dat)) {
    stop("Column F_MISS was not found in ", path)
  }
  dat$F_MISS <- suppressWarnings(as.numeric(dat$F_MISS))
  dat <- dat[!is.na(dat$F_MISS), , drop = FALSE]
  if (nrow(dat) == 0) {
    stop("No numeric F_MISS values were found in ", path)
  }
  dat
}

palette_contract <- c(
  neutral_dark = "#272727",
  neutral_mid = "#767676",
  neutral_light = "#D8D8D8",
  signal_blue = "#3182BD",
  signal_blue_light = "#A6CBE3",
  accent_orange = "#E28E2C"
)

theme_nature <- function(base_size = 6.5, base_family = "Arial") {
  # Nature 风格基础主题：白底、细轴线、小字号、无多余边框。
  theme_classic(base_size = base_size, base_family = base_family) +
    theme(
      axis.line = element_line(linewidth = 0.35, colour = "black"),
      axis.ticks = element_line(linewidth = 0.35, colour = "black"),
      axis.title = element_text(size = base_size),
      axis.text = element_text(size = base_size - 0.4, colour = "black"),
      plot.title = element_text(size = base_size + 0.5, face = "bold", hjust = 0),
      plot.subtitle = element_text(size = base_size - 0.1, colour = palette_contract["neutral_mid"]),
      panel.grid.major.y = element_line(linewidth = 0.2, colour = "#E8E8E8"),
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "none"
    )
}

save_pub <- function(plot, filename, width_mm = 89, height_mm = 66, dpi = 600) {
  # 同时输出可编辑矢量图和高分辨率位图，便于投稿和报告展示。
  width_in <- width_mm / 25.4
  height_in <- height_mm / 25.4
  grDevices::svg(paste0(filename, ".svg"), width = width_in, height = height_in, family = "Arial")
  print(plot)
  dev.off()
  grDevices::cairo_pdf(paste0(filename, ".pdf"), width = width_in, height = height_in, family = "Arial")
  print(plot)
  dev.off()
  grDevices::tiff(paste0(filename, ".tiff"), width = width_in, height = height_in, units = "in", res = dpi, compression = "lzw")
  print(plot)
  dev.off()
}

plot_missing <- function(dat, title, y_label) {
  values <- dat$F_MISS
  stat_label <- sprintf(
    "n = %s\nmean = %.3f\ns.d. = %.3f",
    comma(length(values)),
    mean(values),
    ifelse(length(values) > 1, sd(values), 0)
  )
  ggplot(dat, aes(x = F_MISS)) +
    geom_histogram(
      bins = 30,
      boundary = 0,
      closed = "left",
      fill = palette_contract["signal_blue_light"],
      colour = palette_contract["neutral_dark"],
      linewidth = 0.22
    ) +
    annotate(
      "label",
      x = Inf,
      y = Inf,
      label = stat_label,
      hjust = 1.03,
      vjust = 1.12,
      label.size = 0,
      fill = "white",
      colour = palette_contract["neutral_dark"],
      size = 2.0,
      lineheight = 0.92
    ) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, 0.25),
      labels = label_number(accuracy = 0.01),
      expand = expansion(mult = c(0, 0.02))
    ) +
    scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.08))) +
    labs(title = title, x = "Missing rate", y = y_label) +
    theme_nature()
}

lmiss <- read_missing(lfile)
imiss <- read_missing(ifile)

sample_plot <- plot_missing(imiss, "Sample missingness", "Sample count")
variant_plot <- plot_missing(lmiss, "Variant missingness", "Variant count")

save_pub(sample_plot, paste(prefix, "sample_missing", sep = "."))
save_pub(variant_plot, paste(prefix, "Variant_missing", sep = "."))
