reference: "reference/genome.fa"

container:
    image: "containers/ParaChrSNP.sif"

samples:
    sample1: "raw_fastq/sample1"
    sample2: "raw_fastq/sample2"
    sample3: "raw_fastq/sample3"

params:
    align:
        executable: "bwa"
        bwa_threads: 4
        sort_threads: 2

    mark_duplicates:
        threads: 1
        java_options: "--java-options \"-Xmx10g\""

    haplotype_caller:
        threads: 1
        native_pair_hmm_threads: 1
        java_options: "--java-options \"-Xms512m -Xmx4g\""

    combine_gvcfs:
        threads: 1
        java_options: "--java-options \"-Xms512m -Xmx16g\""

    genotype_gvcfs:
        threads: 1
        java_options: "--java-options \"-Xms512m -Xmx16g\""
